/*

 GEBIRGSPFAD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lgebirgspfadWidth 18
#define lgebirgspfadHeight 1
#define lgebirgspfadBank 0

extern unsigned char lgebirgspfad[];

/* End of GEBIRGSPFAD.H */
