/*

 GEBIRGSPFAD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lgebirgspfadWidth 18
#define lgebirgspfadHeight 1
#define lgebirgspfadBank 0

unsigned char lgebirgspfad[] =
{
  0x4A,0x4A,0x4A,0x78,0x7A,0x7D,0x76,0x6D,0x78,0x6C,
  0x6F,0x79,0x7E,0x7B,0x4A,0x4A,0x4A,0x4A
};

/* End of GEBIRGSPFAD.C */
