/*

 GIPFELPFAD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gipfelpfad_h_INCLUDE
#define __gipfelpfad_h_INCLUDE

#define lgipfelpfadWidth 18
#define lgipfelpfadHeight 1
#define lgipfelpfadBank 0

extern const unsigned char lgipfelpfad[];

#endif

/* End of GIPFELPFAD.H */
