extern const unsigned char leichenwald[];
extern const unsigned char lfeensee[];
extern const unsigned char lseefeendorf[];
extern const unsigned char logerh[];
extern const unsigned char lstadtgefaengnis[];
extern const unsigned char lwiesen[];
extern const unsigned char lfelsengrund[];
extern const unsigned char lelfenhain[];
extern const unsigned char laltebaum[];