extern unsigned char leichenwald[];
extern unsigned char lfeensee[];
extern unsigned char lseefeendorf[];
extern unsigned char logerh[];
extern unsigned char lstadtgefaengnis[];
extern unsigned char lwiesen[];
extern unsigned char lfelsengrund[];
extern unsigned char lelfenhain[];
extern unsigned char laltebaum[];