/*

 MINE3.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lmine3Width 18
#define lmine3Height 1
#define lmine3Bank 0

const unsigned char lmine3[] =
{
  0x4A,0x4A,0x4A,0x4A,0x4A,0x72,0x76,0x71,0x7A,0x4A,
  0x6B,0x78,0x63,0x4A,0x4A,0x4A,0x4A,0x4A
};

/* End of MINE3.C */
