/*

 MINE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mine2_h_INCLUDE
#define __mine2_h_INCLUDE

#define lmine2Width 18
#define lmine2Height 1
#define lmine2Bank 0

extern const unsigned char lmine2[];

#endif

/* End of MINE2.H */
