/*

 MINE3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mine3_h_INCLUDE
#define __mine3_h_INCLUDE

#define lmine3Width 18
#define lmine3Height 1
#define lmine3Bank 0

extern const unsigned char lmine3[];

#endif

/* End of MINE3.H */
