/*

 TEMPELKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tempelkg_h_INCLUDE
#define __tempelkg_h_INCLUDE

#define ltempelkgWidth 18
#define ltempelkgHeight 1
#define ltempelkgBank 0

extern const unsigned char ltempelkg[];

#endif

/* End of TEMPELKG.H */
