/*

 TEMPELE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tempelE1_h_INCLUDE
#define __tempelE1_h_INCLUDE

#define ltempelE1Width 18
#define ltempelE1Height 1
#define ltempelE1Bank 0

extern const unsigned char ltempelE1[];

#endif

/* End of TEMPELE1.H */
