/*

 TEMPELE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tempelE2_h_INCLUDE
#define __tempelE2_h_INCLUDE

#define ltempelE2Width 18
#define ltempelE2Height 1
#define ltempelE2Bank 0

extern const unsigned char ltempelE2[];

#endif

/* End of TEMPELE2.H */
