/*

 V_STATSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_statscreenWidth 20
#define v_statscreenHeight 18
#define v_statscreenBank 0

extern const unsigned char v_statscreen[];

/* End of V_STATSCREEN.H */
