#include "globals.h"

volatile UINT8 v_quit;
BOOLEAN v_nomobs;
unsigned char v_leveldaten [252];
UINT8 v_bank;
UINT8 v_walk;
UINT8 gwalk;
BOOLEAN v_info;
BOOLEAN v_win;
unsigned char v_txt [81];
UINT8 v_lvl;
UINT8 v_truhen [80];    
UINT8 v_schalter [20];           
UINT8 v_knr [10];
UINT8 v_questen [100];   
UINT8 v_aktion;
UINT8 v_bosskampf;                
UINT8 v_kampf;                     
UINT8 v_kampflooptime;
UINT8 v_itemlooptime;
UINT8 v_trefferlooptime;
UINT8 v_i;   
UINT8 v_j;                         
volatile UINT8 v_a;
UINT8 v_b;  
UINT8 v_g;               
UINT8 v_kg;
UINT8 v_pg;
UINT8 v_looptime;
UINT8 v_gameover;         
unsigned char v_tile [3];
UINT8 v_attack;
UINT8 v_aktion2;
UINT8 v_blink; 
UINT8 v_2;
UINT8 v_gxk [3];   
UINT8 v_gyk [3];   
INT8 v_glp [3];         
UINT8 v_gtp [3];
UINT8 v_gmk [4];        
UINT8 v_gri [3];   
UINT8 v_gspf [3];
UINT8 v_gspl [3];
UINT8 v_boss;
UINT8 v_gspeed;         
UINT8 gloop;
UINT8 v_bossloop;
UINT8 v_set;
UINT8 v_stage;
INT8 v_slp;      
INT8 v_smlp;
UINT8 v_saus;
UINT8 v_smaus;
UINT8 v_sxk;      
UINT8 v_syk;      
UINT8 v_sprnr;     
UINT8 v_smk;
UINT8 v_srs;
UINT8 v_stp;       
UINT8 v_sht;      
UINT8 v_smht;     
UINT8 v_sgo;      
UINT8 v_smgo;     
UINT8 v_spr;      
UINT8 v_smpr;
UINT8 v_sstaub;
UINT8 v_smstaub;
UINT8 v_ske;
UINT8 v_ssc;
UINT8 v_sri;
UINT8 v_stref;
UINT8 v_portalrune;
BOOLEAN v_spitzhacke;
BOOLEAN v_sichel;
UINT8 v_portal [4];
UINT8 v_tuer [15];
UINT8 v_shk;
UINT8 v_smhk;
UINT8 v_sat;
UINT8 v_smat;
UINT8 v_smobs;	
UINT8 v_selectItem;
UINT8 v_stein [60];
UINT8 v_busch [40];
BOOLEAN v_sused;
UINT8 v_keyflag;
UINT8 v_imk;
UINT8 v_ixk;
UINT8 v_iyk;
UINT8 v_zufallszahl;
UINT8 v_timer;
UINT8 v_count;
BOOLEAN v_infoscr;
UINT8 v_ausdauertimer;
BOOLEAN v_use_portal; //Portale benutze 1 = ja / 0 = nein
BOOLEAN v_aspekte [3];
UINT8 v_bosseffectloop;
UINT8 v_schaufel;
UINT8 v_loch [10];
