/*

 PHOBETXT2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define phobetxt2Width 18
#define phobetxt2Height 4
#define phobetxt2Bank 0

extern unsigned char phobetxt2[];

/* End of PHOBETXT2.H */
