/*

 ANLEITUNG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __anleitung_h_INCLUDE
#define __anleitung_h_INCLUDE

#define anleitungWidth 20
#define anleitungHeight 18
#define anleitungBank 0

extern const unsigned char anleitung[];

#endif

/* End of ANLEITUNG.H */
