/*

 V_SPRITESET_1.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char v_spriteset_1[] =
{
  0x01,0x01,0x03,0x03,0x06,0x07,0x04,0x07,
  0x04,0x07,0x1E,0x1F,0x1C,0x17,0x1C,0x1B
};

/* End of V_SPRITESET_1.C */
