/*

 ALTE-BAUM-4-38.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 4 to 38

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define altebaumBank 0
/* Start of tile array. */
extern const unsigned char altebaum[];

/* End of ALTE-BAUM-4-38.H */
