/*

 FEENSEE-4-37.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 4 to 37

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define feensee_1Bank 0
/* Start of tile array. */
extern const unsigned char feensee_1[];

/* End of FEENSEE-4-37.H */
