/*

 FELSENGRUND_2-4-19.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 4 to 19

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define felsengrund_2Bank 0
/* Start of tile array. */
extern const unsigned char felsengrund_2[];

/* End of FELSENGRUND_2-4-19.H */
