/*

 GEBIRGSPFAD-3-38.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 3 to 38

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __gebirgspfad_3_38_h_INCLUDE
#define __gebirgspfad_3_38_h_INCLUDE

/* Bank of tiles. */
#define gebirgspfadBank 0
/* Start of tile array. */
extern const unsigned char gebirgspfad[];

#endif

/* End of GEBIRGSPFAD-3-38.H */
