/*

 GRUNDTILES-38-81.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 38 to 81

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define grundtilesBank 0
/* Start of tile array. */
extern unsigned char grundtiles[];

/* End of GRUNDTILES-38-81.H */
