/*

 TEMPEL_KG-3-46.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 3 to 46

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tempel_kg_3_46_h_INCLUDE
#define __tempel_kg_3_46_h_INCLUDE

/* Bank of tiles. */
#define tempel_kgBank 0
/* Start of tile array. */
extern const unsigned char tempel_kg[];

#endif

/* End of TEMPEL_KG-3-46.H */
