#pragma bank=16

/*

 FELSENGRUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

const unsigned char lfelsengrund[] =
{
  0x4A,0x4A,0x4A,0x79,0x7A,0x73,0x6C,0x7A,0x71,0x78,
  0x6D,0x6A,0x71,0x7B,0x4A,0x4A,0x4A,0x4A
};

/* End of FELSENGRUND.C */
