/*

 TITEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define titelWidth 20
#define titelHeight 18
#define titelBank 0

extern unsigned char titel[];

/* End of TITEL.H */
