/*

 K_DORFSEEFEEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 2
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_dorfseefeenWidth 1
#define k_dorfseefeenHeight 2
#define k_dorfseefeenBank 0

extern const unsigned char k_dorfseefeen[];

/* End of K_DORFSEEFEEN.H */
