//#pragma bank=3

/*

 K_EICHENWALD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 6
   Tile set      : c:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\wiesen_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_eichenwaldWidth 5
#define k_eichenwaldHeight 6
#define k_eichenwaldBank 0

const unsigned char k_eichenwald[] =
{
  0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,
  0x35,0x35,0x35,0x00,0x35,0x00,0x35,0x00,0x35,0x00,
  0x35,0x35,0x35,0x35,0x00,0x00,0x00,0x35,0x35,0x35
};

/* End of K_EICHENWALD.C */
