/*

 K_FEENSEE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_feenseeWidth 6
#define k_feenseeHeight 6
#define k_feenseeBank 0

extern const unsigned char k_feensee[];

/* End of K_FEENSEE.H */
