//#pragma bank=3

/*

 K_FELSENGRUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_felsengrundWidth 2
#define k_felsengrundHeight 2
#define k_felsengrundBank 0

const unsigned char k_felsengrund[] =
{
  0x00,0x35,0x35,0x35
};

/* End of K_FELSENGRUND.C */
