/*

 K_OGER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 5
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __k_oger_h_INCLUDE
#define __k_oger_h_INCLUDE

#define k_ogerWidth 8
#define k_ogerHeight 5
#define k_ogerBank 0

extern const unsigned char k_oger[];

#endif

/* End of K_OGER.H */
