/*

 K_TEMPEL_E1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 3
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __k_tempel_e1_h_INCLUDE
#define __k_tempel_e1_h_INCLUDE

#define k_tempel_e1Width 4
#define k_tempel_e1Height 3
#define k_tempel_e1Bank 0

extern const unsigned char k_tempel_e1[];

#endif

/* End of K_TEMPEL_E1.H */
