/*

 K_TEMPEL_E1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 3
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_tempel_e1Width 4
#define k_tempel_e1Height 3
#define k_tempel_e1Bank 0

const unsigned char k_tempel_e1[] =
{
  0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,0x35,
  0x35,0x35
};

/* End of K_TEMPEL_E1.C */
