/*

 K_WIESEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 6
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\wiesen_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_wiesenWidth 9
#define k_wiesenHeight 6
#define k_wiesenBank 0

extern const unsigned char k_wiesen[];

/* End of K_WIESEN.H */
