/*

 NOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 2
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __nomap_h_INCLUDE
#define __nomap_h_INCLUDE

#define nomapWidth 11
#define nomapHeight 2
#define nomapBank 0

extern const unsigned char nomap[];

#endif

/* End of NOMAP.H */
