/*

 NOMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 2
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define nomapWidth 11
#define nomapHeight 2
#define nomapBank 0

const unsigned char nomap[] =
{
  0x74,0x7A,0x76,0x71,0x7A,0x7F,0x74,0x7E,0x6D,0x6B,
  0x7A,0x7F,0x69,0x70,0x6D,0x77,0x7E,0x71,0x7B,0x7A,
  0x71,0x7F
};

/* End of NOMAP.C */
