/*

 NOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 2
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define nomapWidth 11
#define nomapHeight 2
#define nomapBank 0

extern const unsigned char nomap[];

/* End of NOMAP.H */
