/*

 FELSENGRUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/


extern unsigned char lfelsengrund[];

/* End of FELSENGRUND.H */
