#pragma bank=16

/*

 STADTGEFAENGNIS.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lstadtgefaengnisWidth 18
#define lstadtgefaengnisHeight 1
#define lstadtgefaengnisBank 0

const unsigned char lstadtgefaengnis[] =
{
  0x46,0x6C,0x6B,0x7E,0x7B,0x6B,0x78,0x7A,0x79,0x7E,
  0x7A,0x71,0x78,0x71,0x76,0x6C,0x46,0x46
};

/* End of STADTGEFAENGNIS.C */
