/*

 SCHILDTXT1E.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define schildtxt1eWidth 18
#define schildtxt1eHeight 4
#define schildtxt1eBank 0

extern unsigned char schildtxt1e[];

/* End of SCHILDTXT1E.H */
