/*

 HUDGUI.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hudguiWidth 20
#define hudguiHeight 6
#define hudguiBank 0

extern unsigned char hudgui[];

/* End of HUDGUI.H */
