/*

 V_INFOSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_infoscreenWidth 20
#define v_infoscreenHeight 18
#define v_infoscreenBank 0

extern unsigned char v_infoscreen[];

/* End of V_INFOSCREEN.H */
