/*

 HUETERIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hueterin_h_INCLUDE
#define __hueterin_h_INCLUDE

#define hueterintxtWidth 18
#define hueterintxtHeight 4
#define hueterintxtBank 0

extern const unsigned char hueterintxt[];

#endif

/* End of HUETERIN.H */
