//   Verlies - ein Adventure im Retrodesign
//
//   Copyright (C) 2018-2022 Heiko Wolf
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License As published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY Or FITNESS For A PARTICULAR PURPOSE.  See the
//   GNU General Public License For more details.
//
//   You should have received a copy of the GNU General Public License along
//   With this program; if not, write to the Free Software Foundation, Inc.,
//   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//   Kontakt: projekte@kabelmail.net

//#pragma bank=10

/*

 HUETERIN.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hueterintxtWidth 18
#define hueterintxtHeight 4
#define hueterintxtBank 0

const unsigned char hueterintxt[] =
{
  0x76,0x71,0x7F,0x7B,0x76,0x7A,0x6C,0x7A,0x6D,0x7F,
  0x6B,0x6D,0x6A,0x77,0x7A,0x7F,0x00,0x00,0x76,0x6C,
  0x6B,0x7F,0x7B,0x7E,0x6C,0x7F,0x68,0x7E,0x6C,0x7F,
  0x76,0x77,0x6D,0x7F,0x7F,0x7F,0x7D,0x7A,0x7A,0x77,
  0x6D,0x6B,0x5A,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,
  0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,
  0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,0x7F,
  0x51,0x00
};

/* End of HUETERIN.C */
