/*

 KRAEUTERHAENDLER1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\magister\repos\verlies\gfx\entwuerfe\tilesets\eichenwald.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __kraeuterhaendler1_h_INCLUDE
#define __kraeuterhaendler1_h_INCLUDE

#define kraeuterhaendler1Width 18
#define kraeuterhaendler1Height 4
#define kraeuterhaendler1Bank 0

extern const unsigned char kraeuterhaendler1[];

#endif

/* End of KRAEUTERHAENDLER1.H */
