/*

 OGERBOSS2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ogerboss2Width 18
#define ogerboss2Height 4
#define ogerboss2Bank 0

extern const unsigned char ogerboss2[];

/* End of OGERBOSS2.H */
