/*

 PILZWESEN2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\alte-baum.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pilzwesen2Width 18
#define pilzwesen2Height 4
#define pilzwesen2Bank 0

extern const unsigned char pilzwesen2[];

/* End of PILZWESEN2.H */
