/*

 PILZWESEN1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\magister\google-drive\projekte\verlies-16x16\gfx\entwuerfe\tilesets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pilzwesen1Width 18
#define pilzwesen1Height 4
#define pilzwesen1Bank 0

extern const unsigned char pilzwesen1[];

/* End of PILZWESEN1.H */
