/*

 RANARTXT7.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\eichenwald.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ranartxt7Width 18
#define ranartxt7Height 4
#define ranartxt7Bank 0

extern unsigned char ranartxt7[];

/* End of RANARTXT7.H */
