/*

 XAVERTXT17.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\Users\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define xavertxt17Width 18
#define xavertxt17Height 4
#define xavertxt17Bank 0

extern const unsigned char xavertxt17[];

/* End of XAVERTXT17.H */
