/*

 XAVERTXT13.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\Users\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define xavertxt13Width 18
#define xavertxt13Height 4
#define xavertxt13Bank 0

extern const unsigned char xavertxt13[];

/* End of XAVERTXT13.H */
