/*

 XAVERTXT27.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt27_h_INCLUDE
#define __xavertxt27_h_INCLUDE

#define xavertxt27Width 18
#define xavertxt27Height 4
#define xavertxt27Bank 0

extern const unsigned char xavertxt27[];

#endif

/* End of XAVERTXT27.H */
