/*

 XAVERTXT23.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt23_h_INCLUDE
#define __xavertxt23_h_INCLUDE

#define xavertxt23Width 18
#define xavertxt23Height 4
#define xavertxt23Bank 0

extern const unsigned char xavertxt23[];

#endif

/* End of XAVERTXT23.H */
