/*

 XAVERTXT26.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt26_h_INCLUDE
#define __xavertxt26_h_INCLUDE

#define xavertxt26Width 18
#define xavertxt26Height 4
#define xavertxt26Bank 0

extern const unsigned char xavertxt26[];

#endif

/* End of XAVERTXT26.H */
