/*

 XAVERTXT21.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define xavertxt21Width 18
#define xavertxt21Height 4
#define xavertxt21Bank 0

extern unsigned char xavertxt21[];

/* End of XAVERTXT21.H */
