/*

 XAVERTXT9.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt9_h_INCLUDE
#define __xavertxt9_h_INCLUDE

#define xavertxt9Width 18
#define xavertxt9Height 4
#define xavertxt9Bank 0

extern const unsigned char xavertxt9[];

#endif

/* End of XAVERTXT9.H */
