/*

 XAVERTXT24.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt24_h_INCLUDE
#define __xavertxt24_h_INCLUDE

#define xavertxt24Width 18
#define xavertxt24Height 4
#define xavertxt24Bank 0

extern const unsigned char xavertxt24[];

#endif

/* End of XAVERTXT24.H */
