/*

 XAVERTXT28.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __xavertxt28_h_INCLUDE
#define __xavertxt28_h_INCLUDE

#define xavertxt28Width 18
#define xavertxt28Height 4
#define xavertxt28Bank 0

extern const unsigned char xavertxt28[];

#endif

/* End of XAVERTXT28.H */
