/*

 ZAUBERSTAUBHAENDLER1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define zauberstaubhaendler1Width 18
#define zauberstaubhaendler1Height 4
#define zauberstaubhaendler1Bank 0

extern const unsigned char zauberstaubhaendler1[];

/* End of ZAUBERSTAUBHAENDLER1.H */
