//   Verlies - ein Adventure im Retrodesign
//
//   Copyright (C) 2018-2022 Heiko Wolf
//
//   This program is free software; you can redistribute it and/or modify
//   it under the terms of the GNU General Public License As published by
//   the Free Software Foundation; either version 2 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY Or FITNESS For A PARTICULAR PURPOSE.  See the
//   GNU General Public License For more details.
//
//   You should have received a copy of the GNU General Public License along
//   With this program; if not, write to the Free Software Foundation, Inc.,
//   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//
//   Kontakt: projekte@kabelmail.net

/*

 ZYLRA-1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\magister\repos\verlies\gfx\entwuerfe\tilesets\zwergenheim.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define zylratxt1Width 18
#define zylratxt1Height 4
#define zylratxt1Bank 0

unsigned char zylratxt1[] =
{
  0x6C,0x7C,0x77,0x72,0x76,0x7A,0x7B,0x76,0x71,0x00,
  0x65,0x66,0x73,0x6D,0x7E,0x56,0x00,0x00,0x79,0x6A,
  0x7A,0x6D,0x00,0x64,0x55,0x37,0x00,0x6A,0x71,0x7B,
  0x00,0x64,0x60,0x55,0x3B,0x00,0x69,0x7A,0x6D,0x7D,
  0x7A,0x6C,0x6C,0x7A,0x6D,0x7A,0x00,0x76,0x7C,0x77,
  0x00,0x7A,0x6A,0x53,0x6D,0x7A,0x00,0x68,0x7E,0x79,
  0x79,0x7A,0x5A,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x51,0x00
};

/* End of ZYLRA-1.C */
