/*

 ZYLRA-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\magister\repos\verlies\gfx\entwuerfe\tilesets\zwergenheim.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define zylratxt1Width 18
#define zylratxt1Height 4
#define zylratxt1Bank 0

extern unsigned char zylratxt1[];

/* End of ZYLRA-1.H */
