#pragma bank=3

/*

 K_FELSENGRUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

const unsigned char k_felsengrund[] =
{
  0x00,0x00,0x35,0x00,0x00,0x4E,0x35,0x4A,0x35
};

/* End of K_FELSENGRUND.C */
