/*

 INTRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __intro_h_INCLUDE
#define __intro_h_INCLUDE

#define introWidth 18
#define introHeight 4
#define introBank 0

extern const unsigned char intro[];

#endif

/* End of INTRO.H */
