/*

 V_LVL95.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl95Width 18
#define v_lvl95Height 14
#define v_lvl95Bank 0

extern unsigned char v_lvl95[];

/* End of V_LVL95.H */
/*

 V_LVL96.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl96Width 18
#define v_lvl96Height 14
#define v_lvl96Bank 0

extern unsigned char v_lvl96[];

/* End of V_LVL96.H */
/*

 V_LVL97.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl97Width 18
#define v_lvl97Height 14
#define v_lvl97Bank 0

extern unsigned char v_lvl97[];

/* End of V_LVL97.H */
/*

 V_LVL98.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl98Width 18
#define v_lvl98Height 14
#define v_lvl98Bank 0

extern unsigned char v_lvl98[];

/* End of V_LVL98.H */
/*

 V_LVL99.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl99Width 18
#define v_lvl99Height 14
#define v_lvl99Bank 0

extern unsigned char v_lvl99[];

/* End of V_LVL99.H */
/*

 V_LVL100.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl100Width 18
#define v_lvl100Height 14
#define v_lvl100Bank 0

extern unsigned char v_lvl100[];

/* End of V_LVL100.H */
/*

 V_LVL101.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl101Width 18
#define v_lvl101Height 14
#define v_lvl101Bank 0

extern unsigned char v_lvl101[];

/* End of V_LVL101.H */
/*

 V_LVL102.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl102Width 18
#define v_lvl102Height 14
#define v_lvl102Bank 0

extern unsigned char v_lvl102[];

/* End of V_LVL102.H */
/*

 V_LVL103.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl103Width 18
#define v_lvl103Height 14
#define v_lvl103Bank 0

extern unsigned char v_lvl103[];

/* End of V_LVL103.H */
/*

 V_LVL104.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl104Width 18
#define v_lvl104Height 14
#define v_lvl104Bank 0

extern unsigned char v_lvl104[];

/* End of V_LVL104.H */
/*

 V_LVL105.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl105Width 18
#define v_lvl105Height 14
#define v_lvl105Bank 0

extern unsigned char v_lvl105[];

/* End of V_LVL105.H */
/*

 V_LVL106.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl106Width 18
#define v_lvl106Height 14
#define v_lvl106Bank 0

extern unsigned char v_lvl106[];

/* End of V_LVL106.H */
/*

 V_LVL107.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl107Width 18
#define v_lvl107Height 14
#define v_lvl107Bank 0

extern unsigned char v_lvl107[];

/* End of V_LVL107.H */
/*

 V_LVL108.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl108Width 18
#define v_lvl108Height 14
#define v_lvl108Bank 0

extern unsigned char v_lvl108[];

/* End of V_LVL108.H */
/*

 V_LVL109.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl109Width 18
#define v_lvl109Height 14
#define v_lvl109Bank 0

extern unsigned char v_lvl109[];

/* End of V_LVL109.H */
/*

 V_LVL110.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl110Width 18
#define v_lvl110Height 14
#define v_lvl110Bank 0

extern unsigned char v_lvl110[];

/* End of V_LVL110.H */
/*

 V_LVL111.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl111Width 18
#define v_lvl111Height 14
#define v_lvl111Bank 0

extern unsigned char v_lvl111[];

/* End of V_LVL111.H */
/*

 V_LVL112.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl112Width 18
#define v_lvl112Height 14
#define v_lvl112Bank 0

extern unsigned char v_lvl112[];

/* End of V_LVL112.H */
/*

 V_LVL113.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl113Width 18
#define v_lvl113Height 14
#define v_lvl113Bank 0

extern unsigned char v_lvl113[];

/* End of V_LVL113.H */
/*

 V_LVL114.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl114Width 18
#define v_lvl114Height 14
#define v_lvl114Bank 0

extern unsigned char v_lvl114[];

/* End of V_LVL114.H */
/*

 V_LVL115.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl115Width 18
#define v_lvl115Height 14
#define v_lvl115Bank 0

extern unsigned char v_lvl115[];

/* End of V_LVL115.H */
/*

 V_LVL116.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl116Width 18
#define v_lvl116Height 14
#define v_lvl116Bank 0

extern unsigned char v_lvl116[];

/* End of V_LVL116.H */
/*

 V_LVL117.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl117Width 18
#define v_lvl117Height 14
#define v_lvl117Bank 0

extern unsigned char v_lvl117[];

/* End of V_LVL117.H */
