/*

 V_LVL290.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl290_h_INCLUDE
#define __v_lvl290_h_INCLUDE

#define v_lvl290Width 18
#define v_lvl290Height 14
#define v_lvl290Bank 0

extern const unsigned char v_lvl290[];

#endif

/* End of V_LVL290.H */
/*

 V_LVL291.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl291_h_INCLUDE
#define __v_lvl291_h_INCLUDE

#define v_lvl291Width 18
#define v_lvl291Height 14
#define v_lvl291Bank 0

extern const unsigned char v_lvl291[];

#endif

/* End of V_LVL291.H */
/*

 V_LVL292.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl292_h_INCLUDE
#define __v_lvl292_h_INCLUDE

#define v_lvl292Width 18
#define v_lvl292Height 14
#define v_lvl292Bank 0

extern const unsigned char v_lvl292[];

#endif

/* End of V_LVL292.H */
/*

 V_LVL293.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl293_h_INCLUDE
#define __v_lvl293_h_INCLUDE

#define v_lvl293Width 18
#define v_lvl293Height 14
#define v_lvl293Bank 0

extern const unsigned char v_lvl293[];

#endif

/* End of V_LVL293.H */
/*

 V_LVL294.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl294_h_INCLUDE
#define __v_lvl294_h_INCLUDE

#define v_lvl294Width 18
#define v_lvl294Height 14
#define v_lvl294Bank 0

extern const unsigned char v_lvl294[];

#endif

/* End of V_LVL294.H */
/*

 V_LVL295.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl295_h_INCLUDE
#define __v_lvl295_h_INCLUDE

#define v_lvl295Width 18
#define v_lvl295Height 14
#define v_lvl295Bank 0

extern const unsigned char v_lvl295[];

#endif

/* End of V_LVL295.H */
