/*

 V_LVL220.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl220_h_INCLUDE
#define __v_lvl220_h_INCLUDE

#define v_lvl220Width 18
#define v_lvl220Height 14
#define v_lvl220Bank 0

extern const unsigned char v_lvl220[];

#endif

/* End of V_LVL220.H */
/*

 V_LVL221.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl221_h_INCLUDE
#define __v_lvl221_h_INCLUDE

#define v_lvl221Width 18
#define v_lvl221Height 14
#define v_lvl221Bank 0

extern const unsigned char v_lvl221[];

#endif

/* End of V_LVL221.H */
/*

 V_LVL222.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl222_h_INCLUDE
#define __v_lvl222_h_INCLUDE

#define v_lvl222Width 18
#define v_lvl222Height 14
#define v_lvl222Bank 0

extern const unsigned char v_lvl222[];

#endif

/* End of V_LVL222.H */
/*

 V_LVL223.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl223_h_INCLUDE
#define __v_lvl223_h_INCLUDE

#define v_lvl223Width 18
#define v_lvl223Height 14
#define v_lvl223Bank 0

extern const unsigned char v_lvl223[];

#endif

/* End of V_LVL223.H */
/*

 V_LVL224.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl224_h_INCLUDE
#define __v_lvl224_h_INCLUDE

#define v_lvl224Width 18
#define v_lvl224Height 14
#define v_lvl224Bank 0

extern const unsigned char v_lvl224[];

#endif

/* End of V_LVL224.H */
/*

 V_LVL225.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl225_h_INCLUDE
#define __v_lvl225_h_INCLUDE

#define v_lvl225Width 18
#define v_lvl225Height 14
#define v_lvl225Bank 0

extern const unsigned char v_lvl225[];

#endif

/* End of V_LVL225.H */
/*

 V_LVL226.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl226_h_INCLUDE
#define __v_lvl226_h_INCLUDE

#define v_lvl226Width 18
#define v_lvl226Height 14
#define v_lvl226Bank 0

extern const unsigned char v_lvl226[];

#endif

/* End of V_LVL226.H */
/*

 V_LVL227.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl227_h_INCLUDE
#define __v_lvl227_h_INCLUDE

#define v_lvl227Width 18
#define v_lvl227Height 14
#define v_lvl227Bank 0

extern const unsigned char v_lvl227[];

#endif

/* End of V_LVL227.H */
/*

 V_LVL228.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl228_h_INCLUDE
#define __v_lvl228_h_INCLUDE

#define v_lvl228Width 18
#define v_lvl228Height 14
#define v_lvl228Bank 0

extern const unsigned char v_lvl228[];

#endif

/* End of V_LVL228.H */
/*

 V_LVL229.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl229_h_INCLUDE
#define __v_lvl229_h_INCLUDE

#define v_lvl229Width 18
#define v_lvl229Height 14
#define v_lvl229Bank 0

extern const unsigned char v_lvl229[];

#endif

/* End of V_LVL229.H */
/*

 V_LVL230.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl230_h_INCLUDE
#define __v_lvl230_h_INCLUDE

#define v_lvl230Width 18
#define v_lvl230Height 14
#define v_lvl230Bank 0

extern const unsigned char v_lvl230[];

#endif

/* End of V_LVL230.H */
/*

 V_LVL231.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl231_h_INCLUDE
#define __v_lvl231_h_INCLUDE

#define v_lvl231Width 18
#define v_lvl231Height 14
#define v_lvl231Bank 0

extern const unsigned char v_lvl231[];

#endif

/* End of V_LVL231.H */
