/*

 V_LVL260.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl260_h_INCLUDE
#define __v_lvl260_h_INCLUDE

#define v_lvl260Width 18
#define v_lvl260Height 14
#define v_lvl260Bank 0

extern const unsigned char v_lvl260[];

#endif

/* End of V_LVL260.H */
/*

 V_LVL261.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl261_h_INCLUDE
#define __v_lvl261_h_INCLUDE

#define v_lvl261Width 18
#define v_lvl261Height 14
#define v_lvl261Bank 0

extern const unsigned char v_lvl261[];

#endif

/* End of V_LVL261.H */
/*

 V_LVL262.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl262_h_INCLUDE
#define __v_lvl262_h_INCLUDE

#define v_lvl262Width 18
#define v_lvl262Height 14
#define v_lvl262Bank 0

extern const unsigned char v_lvl262[];

#endif

/* End of V_LVL262.H */
/*

 V_LVL263.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl263_h_INCLUDE
#define __v_lvl263_h_INCLUDE

#define v_lvl263Width 18
#define v_lvl263Height 14
#define v_lvl263Bank 0

extern const unsigned char v_lvl263[];

#endif

/* End of V_LVL263.H */
/*

 V_LVL264.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl264_h_INCLUDE
#define __v_lvl264_h_INCLUDE

#define v_lvl264Width 18
#define v_lvl264Height 14
#define v_lvl264Bank 0

extern const unsigned char v_lvl264[];

#endif

/* End of V_LVL264.H */
/*

 V_LVL265.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl265_h_INCLUDE
#define __v_lvl265_h_INCLUDE

#define v_lvl265Width 18
#define v_lvl265Height 14
#define v_lvl265Bank 0

extern const unsigned char v_lvl265[];

#endif

/* End of V_LVL265.H */
/*

 V_LVL266.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl266_h_INCLUDE
#define __v_lvl266_h_INCLUDE

#define v_lvl266Width 18
#define v_lvl266Height 14
#define v_lvl266Bank 0

extern const unsigned char v_lvl266[];

#endif

/* End of V_LVL266.H */
/*

 V_LVL267.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl267_h_INCLUDE
#define __v_lvl267_h_INCLUDE

#define v_lvl267Width 18
#define v_lvl267Height 14
#define v_lvl267Bank 0

extern const unsigned char v_lvl267[];

#endif

/* End of V_LVL267.H */
/*

 V_LVL268.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl268_h_INCLUDE
#define __v_lvl268_h_INCLUDE

#define v_lvl268Width 18
#define v_lvl268Height 14
#define v_lvl268Bank 0

extern const unsigned char v_lvl268[];

#endif

/* End of V_LVL268.H */
/*

 V_LVL269.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl269_h_INCLUDE
#define __v_lvl269_h_INCLUDE

#define v_lvl269Width 18
#define v_lvl269Height 14
#define v_lvl269Bank 0

extern const unsigned char v_lvl269[];

#endif

/* End of V_LVL269.H */
/*

 V_LVL270.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl270_h_INCLUDE
#define __v_lvl270_h_INCLUDE

#define v_lvl270Width 18
#define v_lvl270Height 14
#define v_lvl270Bank 0

extern const unsigned char v_lvl270[];

#endif

/* End of V_LVL270.H */
