/*

 V_LVL40.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl40Width 18
#define v_lvl40Height 14
#define v_lvl40Bank 0

extern const unsigned char v_lvl40[];

/* End of V_LVL40.H */
/*

 V_LVL41.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl41Width 18
#define v_lvl41Height 14
#define v_lvl41Bank 0

extern unsigned char v_lvl41[];

/* End of V_LVL41.H */
/*

 V_LVL42.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl42Width 18
#define v_lvl42Height 14
#define v_lvl42Bank 0

extern unsigned char v_lvl42[];

/* End of V_LVL42.H */
/*

 V_LVL43.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl43Width 18
#define v_lvl43Height 14
#define v_lvl43Bank 0

extern unsigned char v_lvl43[];

/* End of V_LVL43.H */
/*

 V_LVL44.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl44Width 18
#define v_lvl44Height 14
#define v_lvl44Bank 0

extern unsigned char v_lvl44[];

/* End of V_LVL44.H */
/*

 V_LVL45.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl45Width 18
#define v_lvl45Height 14
#define v_lvl45Bank 0

extern unsigned char v_lvl45[];

/* End of V_LVL45.H */
/*

 V_LVL46.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl46Width 18
#define v_lvl46Height 14
#define v_lvl46Bank 0

extern unsigned char v_lvl46[];

/* End of V_LVL46.H */
/*

 V_LVL47.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl47Width 18
#define v_lvl47Height 14
#define v_lvl47Bank 0

extern unsigned char v_lvl47[];

/* End of V_LVL47.H */
/*

 V_LVL48.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl48Width 18
#define v_lvl48Height 14
#define v_lvl48Bank 0

extern unsigned char v_lvl48[];

/* End of V_LVL48.H */
/*

 V_LVL49.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl49Width 18
#define v_lvl49Height 14
#define v_lvl49Bank 0

extern unsigned char v_lvl49[];

/* End of V_LVL49.H */
/*

 V_LVL50.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl50Width 18
#define v_lvl50Height 14
#define v_lvl50Bank 0

extern unsigned char v_lvl50[];

/* End of V_LVL50.H */
/*

 V_LVL51.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl51Width 18
#define v_lvl51Height 14
#define v_lvl51Bank 0

extern unsigned char v_lvl51[];

/* End of V_LVL51.H */
/*

 V_LVL52.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl52Width 18
#define v_lvl52Height 14
#define v_lvl52Bank 0

extern unsigned char v_lvl52[];

/* End of V_LVL52.H */
/*

 V_LVL53.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl53Width 18
#define v_lvl53Height 14
#define v_lvl53Bank 0

extern unsigned char v_lvl53[];

/* End of V_LVL53.H */
/*

 V_LVL54.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl54Width 18
#define v_lvl54Height 14
#define v_lvl54Bank 0

extern unsigned char v_lvl54[];

/* End of V_LVL54.H */
/*

 V_LVL55.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl55Width 18
#define v_lvl55Height 14
#define v_lvl55Bank 0

extern unsigned char v_lvl55[];

/* End of V_LVL55.H */
/*

 V_LVL56.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl56Width 18
#define v_lvl56Height 14
#define v_lvl56Bank 0

extern unsigned char v_lvl56[];

/* End of V_LVL56.H */
/*

 V_LVL57.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl57Width 18
#define v_lvl57Height 14
#define v_lvl57Bank 0

extern unsigned char v_lvl57[];

/* End of V_LVL57.H */
/*

 V_LVL58.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl58Width 18
#define v_lvl58Height 14
#define v_lvl58Bank 0

extern unsigned char v_lvl58[];

/* End of V_LVL58.H */
/*

 V_LVL59.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl59Width 18
#define v_lvl59Height 14
#define v_lvl59Bank 0

extern unsigned char v_lvl59[];

/* End of V_LVL59.H */
/*

 V_LVL60.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl60Width 18
#define v_lvl60Height 14
#define v_lvl60Bank 0

extern unsigned char v_lvl60[];

/* End of V_LVL60.H */
/*

 V_LVL61.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl61Width 18
#define v_lvl61Height 14
#define v_lvl61Bank 0

extern unsigned char v_lvl61[];

/* End of V_LVL61.H */
/*

 V_LVL62.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl62Width 18
#define v_lvl62Height 14
#define v_lvl62Bank 0

extern unsigned char v_lvl62[];

/* End of V_LVL62.H */
/*

 V_LVL63.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl63Width 18
#define v_lvl63Height 14
#define v_lvl63Bank 0

extern unsigned char v_lvl63[];

/* End of V_LVL63.H */
/*

 V_LVL64.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl64Width 18
#define v_lvl64Height 14
#define v_lvl64Bank 0

extern unsigned char v_lvl64[];

/* End of V_LVL64.H */
/*

 V_LVL65.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl65Width 18
#define v_lvl65Height 14
#define v_lvl65Bank 0

extern unsigned char v_lvl65[];

/* End of V_LVL65.H */
/*

 V_LVL66.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl66Width 18
#define v_lvl66Height 14
#define v_lvl66Bank 0

extern unsigned char v_lvl66[];

/* End of V_LVL66.H */
