/*

 V_LVL275.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl275_h_INCLUDE
#define __v_lvl275_h_INCLUDE

#define v_lvl275Width 18
#define v_lvl275Height 14
#define v_lvl275Bank 0

extern const unsigned char v_lvl275[];

#endif

/* End of V_LVL275.H */
/*

 V_LVL276.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl276_h_INCLUDE
#define __v_lvl276_h_INCLUDE

#define v_lvl276Width 18
#define v_lvl276Height 14
#define v_lvl276Bank 0

extern const unsigned char v_lvl276[];

#endif

/* End of V_LVL276.H */
/*

 V_LVL277.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl277_h_INCLUDE
#define __v_lvl277_h_INCLUDE

#define v_lvl277Width 18
#define v_lvl277Height 14
#define v_lvl277Bank 0

extern const unsigned char v_lvl277[];

#endif

/* End of V_LVL277.H */
/*

 V_LVL278.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl278_h_INCLUDE
#define __v_lvl278_h_INCLUDE

#define v_lvl278Width 18
#define v_lvl278Height 14
#define v_lvl278Bank 0

extern const unsigned char v_lvl278[];

#endif

/* End of V_LVL278.H */
/*

 V_LVL279.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl279_h_INCLUDE
#define __v_lvl279_h_INCLUDE

#define v_lvl279Width 18
#define v_lvl279Height 14
#define v_lvl279Bank 0

extern const unsigned char v_lvl279[];

#endif

/* End of V_LVL279.H */
/*

 V_LVL280.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl280_h_INCLUDE
#define __v_lvl280_h_INCLUDE

#define v_lvl280Width 18
#define v_lvl280Height 14
#define v_lvl280Bank 0

extern const unsigned char v_lvl280[];

#endif

/* End of V_LVL280.H */
/*

 V_LVL281.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl281_h_INCLUDE
#define __v_lvl281_h_INCLUDE

#define v_lvl281Width 18
#define v_lvl281Height 14
#define v_lvl281Bank 0

extern const unsigned char v_lvl281[];

#endif

/* End of V_LVL281.H */
/*

 V_LVL282.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl282_h_INCLUDE
#define __v_lvl282_h_INCLUDE

#define v_lvl282Width 18
#define v_lvl282Height 14
#define v_lvl282Bank 0

extern const unsigned char v_lvl282[];

#endif

/* End of V_LVL282.H */
/*

 V_LVL283.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl283_h_INCLUDE
#define __v_lvl283_h_INCLUDE

#define v_lvl283Width 18
#define v_lvl283Height 14
#define v_lvl283Bank 0

extern const unsigned char v_lvl283[];

#endif

/* End of V_LVL283.H */
/*

 V_LVL284.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl284_h_INCLUDE
#define __v_lvl284_h_INCLUDE

#define v_lvl284Width 18
#define v_lvl284Height 14
#define v_lvl284Bank 0

extern const unsigned char v_lvl284[];

#endif

/* End of V_LVL284.H */
/*

 V_LVL285.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl285_h_INCLUDE
#define __v_lvl285_h_INCLUDE

#define v_lvl285Width 18
#define v_lvl285Height 14
#define v_lvl285Bank 0

extern const unsigned char v_lvl285[];

#endif

/* End of V_LVL285.H */
/*

 V_LVL286.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl286_h_INCLUDE
#define __v_lvl286_h_INCLUDE

#define v_lvl286Width 18
#define v_lvl286Height 14
#define v_lvl286Bank 0

extern const unsigned char v_lvl286[];

#endif

/* End of V_LVL286.H */
/*

 V_LVL287.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl287_h_INCLUDE
#define __v_lvl287_h_INCLUDE

#define v_lvl287Width 18
#define v_lvl287Height 14
#define v_lvl287Bank 0

extern const unsigned char v_lvl287[];

#endif

/* End of V_LVL287.H */
