/*

 V_LVL90.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl90Width 18
#define v_lvl90Height 14
#define v_lvl90Bank 0

extern const unsigned char v_lvl90[];

/* End of V_LVL90.H */
/*

 V_LVL91.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl91Width 18
#define v_lvl91Height 14
#define v_lvl91Bank 0

extern unsigned char v_lvl91[];

/* End of V_LVL91.H */
