/*

 V_LVL206.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl206_h_INCLUDE
#define __v_lvl206_h_INCLUDE

#define v_lvl206Width 18
#define v_lvl206Height 14
#define v_lvl206Bank 0

extern const unsigned char v_lvl205[];

extern const unsigned char v_lvl206[];

#endif

/* End of V_LVL206.H */
/*

 V_LVL207.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl207_h_INCLUDE
#define __v_lvl207_h_INCLUDE

#define v_lvl207Width 18
#define v_lvl207Height 14
#define v_lvl207Bank 0

extern const unsigned char v_lvl207[];

#endif

/* End of V_LVL207.H */
/*

 V_LVL208.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl208_h_INCLUDE
#define __v_lvl208_h_INCLUDE

#define v_lvl217Width 18
#define v_lvl217Height 14
#define v_lvl217Bank 0

extern const unsigned char v_lvl208[];

#endif

/* End of V_LVL208.H */
/*

 V_LVL209.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl209_h_INCLUDE
#define __v_lvl209_h_INCLUDE

#define v_lvl209Width 18
#define v_lvl209Height 14
#define v_lvl209Bank 0

extern const unsigned char v_lvl209[];

#endif

/* End of V_LVL209.H */
/*

 V_LVL210.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl210_h_INCLUDE
#define __v_lvl210_h_INCLUDE

#define v_lvl210Width 18
#define v_lvl210Height 14
#define v_lvl210Bank 0

extern const unsigned char v_lvl210[];

#endif

/* End of V_LVL210.H */
/*

 V_LVL211.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl211_h_INCLUDE
#define __v_lvl211_h_INCLUDE

#define v_lvl211Width 18
#define v_lvl211Height 14
#define v_lvl211Bank 0

extern const unsigned char v_lvl211[];

#endif

/* End of V_LVL211.H */
/*

 V_LVL212.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl212_h_INCLUDE
#define __v_lvl212_h_INCLUDE

#define v_lvl212Width 18
#define v_lvl212Height 14
#define v_lvl212Bank 0

extern const unsigned char v_lvl212[];

#endif

/* End of V_LVL212.H */
/*

 V_LVL213.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl213_h_INCLUDE
#define __v_lvl213_h_INCLUDE

#define v_lvl213Width 18
#define v_lvl213Height 14
#define v_lvl213Bank 0

extern const unsigned char v_lvl213[];

#endif

/* End of V_LVL213.H */
/*

 V_LVL214.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl214_h_INCLUDE
#define __v_lvl214_h_INCLUDE

#define v_lvl214Width 18
#define v_lvl214Height 14
#define v_lvl214Bank 0

extern const unsigned char v_lvl214[];

#endif

/* End of V_LVL214.H */
/*

 V_LVL215.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl215_h_INCLUDE
#define __v_lvl215_h_INCLUDE

#define v_lvl215Width 18
#define v_lvl215Height 14
#define v_lvl215Bank 0

extern const unsigned char v_lvl215[];

#endif

/* End of V_LVL215.H */
/*

 V_LVL216.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl216_h_INCLUDE
#define __v_lvl216_h_INCLUDE

#define v_lvl216Width 18
#define v_lvl216Height 14
#define v_lvl216Bank 0

extern const unsigned char v_lvl216[];

#endif

/* End of V_LVL216.H */
/*

 V_LVL217.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl217_h_INCLUDE
#define __v_lvl217_h_INCLUDE

#define v_lvl217Width 18
#define v_lvl217Height 14
#define v_lvl217Bank 0

extern const unsigned char v_lvl217[];

#endif

/* End of V_LVL217.H */
