/*

 V_LVL239.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl239_h_INCLUDE
#define __v_lvl239_h_INCLUDE

#define v_lvl239Width 18
#define v_lvl239Height 14
#define v_lvl239Bank 0

extern const unsigned char v_lvl239[];

#endif

/* End of V_LVL239.H */
