/*

 V_LVL193.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl193Width 18
#define v_lvl193Height 14
#define v_lvl193Bank 0

extern unsigned char v_lvl193[];

/* End of V_LVL193.H */
