/*

 V_LVL76.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\wiesen_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl76Width 18
#define v_lvl76Height 14
#define v_lvl76Bank 0

extern unsigned char v_lvl76[];

/* End of V_LVL76.H */
