/*

 V_LVL226.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl226_h_INCLUDE
#define __v_lvl226_h_INCLUDE

#define v_lvl226Width 18
#define v_lvl226Height 14
#define v_lvl226Bank 0

extern const unsigned char v_lvl226[];

#endif

/* End of V_LVL226.H */
