/*

 V_LVL125.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : C:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\eichenwald.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl125Width 18
#define v_lvl125Height 14
#define v_lvl125Bank 0

extern unsigned char v_lvl125[];

/* End of V_LVL125.H */
