/*

 V_LVL126.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : C:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\eichenwald.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl126Width 18
#define v_lvl126Height 14
#define v_lvl126Bank 0

extern unsigned char v_lvl126[];

/* End of V_LVL126.H */
