/*

 V_LVL268.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl268_h_INCLUDE
#define __v_lvl268_h_INCLUDE

#define v_lvl268Width 18
#define v_lvl268Height 14
#define v_lvl268Bank 0

extern const unsigned char v_lvl268[];

#endif

/* End of V_LVL268.H */
