/*

 V_LVL277.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-1E.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl277_h_INCLUDE
#define __v_lvl277_h_INCLUDE

#define v_lvl277Width 18
#define v_lvl277Height 14
#define v_lvl277Bank 0

extern const unsigned char v_lvl277[];

#endif

/* End of V_LVL277.H */
