/*

 V_LVL236.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __v_lvl236_h_INCLUDE
#define __v_lvl236_h_INCLUDE

#define v_lvl236Width 18
#define v_lvl236Height 14
#define v_lvl236Bank 0

extern const unsigned char v_lvl236[];

#endif

/* End of V_LVL236.H */
