/*

 V_LVL166.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\alte-baum.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl166Width 18
#define v_lvl166Height 14
#define v_lvl166Bank 0

extern const unsigned char v_lvl166[];

/* End of V_LVL166.H */
