#pragma bank=8

/*

 K_FELSENGRUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 3 x 3
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_felsengrundWidth 3
#define k_felsengrundHeight 3
#define k_felsengrundBank 0

const unsigned char k_felsengrund[] =
{
  0x00,0x00,0x2F,0x00,0x00,0x4A,0x2F,0x46,0x2F
};

/* End of K_FELSENGRUND.C */
