/*

 K_GEFAENGNIS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 7 x 6
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define k_gefaengnisWidth 7
#define k_gefaengnisHeight 6
#define k_gefaengnisBank 0

extern unsigned char k_gefaengnis[];

/* End of K_GEFAENGNIS.H */
