/*

 PORTALABBRECHEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portalabbrechenWidth 18
#define portalabbrechenHeight 1
#define portalabbrechenBank 0

extern const unsigned char portalabbrechen[];

/* End of PORTALABBRECHEN.H */
