/*

 PORTAL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __portal2_h_INCLUDE
#define __portal2_h_INCLUDE

#define portal2Width 18
#define portal2Height 1
#define portal2Bank 0

extern const unsigned char portal2[];

#endif

/* End of PORTAL2.H */
