//#pragma bank=8

/*

 PORTALABBRECHEN.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portalabbrechenWidth 18
#define portalabbrechenHeight 1
#define portalabbrechenBank 0

const unsigned char portalabbrechen[] =
{
  0x51,0x00,0x00,0x00,0x00,0x00,0x53,0x00,0x7E,0x7D,
  0x7D,0x6D,0x7A,0x7C,0x77,0x7A,0x71,0x00
};

/* End of PORTALABBRECHEN.C */
