/*

 PORTAL4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\zwergenheim.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __portal4_h_INCLUDE
#define __portal4_h_INCLUDE

#define portal4Width 18
#define portal4Height 1
#define portal4Bank 0

extern const unsigned char portal4[];

#endif

/* End of PORTAL4.H */
