/*

 PORTAL2.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\feensee.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portal2Width 18
#define portal2Height 1
#define portal2Bank 0

const unsigned char portal2[] =
{
  0x7B,0x70,0x68,0x71,0x7F,0x7F,0x53,0x00,0x6C,0x7A,
  0x7A,0x79,0x7A,0x7A,0x71,0x7B,0x59,0x7F
};

/* End of PORTAL2.C */
