/*

 PORTAL1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portal1Width 18
#define portal1Height 1
#define portal1Bank 0

const unsigned char portal1[] =
{
  0x6A,0x6F,0x7F,0x7F,0x7F,0x7F,0x53,0x00,0x79,0x7A,
  0x73,0x6C,0x7A,0x71,0x78,0x6D,0x59,0x7F
};

/* End of PORTAL1.C */
