/*

 PORTAL4.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\zwergenheim.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portal4Width 18
#define portal4Height 1
#define portal4Bank 0

const unsigned char portal4[] =
{
  0x6D,0x7A,0x7C,0x77,0x6B,0x6C,0x7F,0x53,0x7F,0x65,
  0x68,0x7A,0x6D,0x78,0x7A,0x71,0x77,0x59
};

/* End of PORTAL4.C */
