/*

 PORTAL3.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\eichenwald.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define portal3Width 18
#define portal3Height 1
#define portal3Bank 0

const unsigned char portal3[] =
{
  0x73,0x7A,0x79,0x6B,0x7F,0x7F,0x53,0x7F,0x7A,0x73,
  0x79,0x7A,0x71,0x77,0x7E,0x76,0x71,0x7F
};

/* End of PORTAL3.C */
