/*

 V_LVL1A.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define v_lvl1aWidth 18
#define v_lvl1aHeight 14
#define v_lvl1aBank 0

extern unsigned char v_lvl1a[];

/* End of V_LVL1A.H */
