/*

 ASPEKTWALD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\alte-baum.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define aspektwaldWidth 18
#define aspektwaldHeight 4
#define aspektwaldBank 0

extern unsigned char aspektwald[];

/* End of ASPEKTWALD.H */
