/*

 ASPEKTBERG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\alte-baum.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __aspektberg_h_INCLUDE
#define __aspektberg_h_INCLUDE

#define aspektbergWidth 18
#define aspektbergHeight 4
#define aspektbergBank 0

extern const unsigned char aspektberg[];

#endif

/* End of ASPEKTBERG.H */
