/*

 AUSDAUERTRANK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ausdauertrankWidth 18
#define ausdauertrankHeight 4
#define ausdauertrankBank 0

extern const unsigned char ausdauertrank[];

/* End of AUSDAUERTRANK.H */
