/*

 BROTBUECHSE-2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : C:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define brotbuechse_2Width 18
#define brotbuechse_2Height 4
#define brotbuechse_2Bank 0

extern const unsigned char brotbuechse_2[];

/* End of BROTBUECHSE-2.H */
