/*

 BROTBUECHSE-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define brotbuechse_1Width 18
#define brotbuechse_1Height 4
#define brotbuechse_1Bank 0

extern const unsigned char brotbuechse_1[];

/* End of BROTBUECHSE-1.H */
