/*

 GELDKATZE2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define geldkatze2Width 18
#define geldkatze2Height 4
#define geldkatze2Bank 0

extern const unsigned char geldkatze2[];

/* End of GELDKATZE2.H */
