/*

 HEILTRANK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __heiltrank_h_INCLUDE
#define __heiltrank_h_INCLUDE

#define heiltrankWidth 18
#define heiltrankHeight 4
#define heiltrankBank 0

extern const unsigned char heiltrank[];

#endif

/* End of HEILTRANK.H */
