/*

 HEILTRANK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define heiltrankWidth 18
#define heiltrankHeight 4
#define heiltrankBank 0

extern const unsigned char heiltrank[];

/* End of HEILTRANK.H */
