/*

 KARTETRUHE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\stadtgefaengnis_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define kartetruheWidth 18
#define kartetruheHeight 4
#define kartetruheBank 0

extern const unsigned char kartetruhe[];

/* End of KARTETRUHE.H */
