/*

 KRAEUTERBEUTEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __kraeuterbeutel_h_INCLUDE
#define __kraeuterbeutel_h_INCLUDE

#define kraeuterbeutelWidth 18
#define kraeuterbeutelHeight 4
#define kraeuterbeutelBank 0

extern const unsigned char kraeuterbeutel[];

#endif

/* End of KRAEUTERBEUTEL.H */
