/*

 PORTALRUNE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __portalrune_h_INCLUDE
#define __portalrune_h_INCLUDE

#define portalruneWidth 18
#define portalruneHeight 4
#define portalruneBank 0

extern const unsigned char portalrune[];

#endif

/* End of PORTALRUNE.H */
