/*

 SCHAUFEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __schaufel_h_INCLUDE
#define __schaufel_h_INCLUDE

#define schaufelWidth 18
#define schaufelHeight 4
#define schaufelBank 0

extern const unsigned char schaufel[];

#endif

/* End of SCHAUFEL.H */
