/*

 SCHLUESSEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\ogerhoehlen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tschluesselWidth 18
#define tschluesselHeight 4
#define tschluesselBank 0

extern unsigned char tschluessel[];

/* End of SCHLUESSEL.H */
