/*

 STOFF.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __stoff_h_INCLUDE
#define __stoff_h_INCLUDE

#define stoffWidth 18
#define stoffHeight 4
#define stoffBank 0

extern const unsigned char stoff[];

#endif

/* End of STOFF.H */
