/*

 WAPPENROCK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\grundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define wappenrockWidth 18
#define wappenrockHeight 4
#define wappenrockBank 0

extern unsigned char wappenrock[];

/* End of WAPPENROCK.H */
