/*

 ZAUBERSTAUB.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __zauberstaub_h_INCLUDE
#define __zauberstaub_h_INCLUDE

#define zauberstaubWidth 18
#define zauberstaubHeight 4
#define zauberstaubBank 0

extern const unsigned char zauberstaub[];

#endif

/* End of ZAUBERSTAUB.H */
