/*

 SCHILDTXT5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define schildtxt5Width 18
#define schildtxt5Height 4
#define schildtxt5Bank 0

extern const unsigned char schildtxt5[];

/* End of SCHILDTXT5.H */
