/*

 SCHILDTXT10.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\gebirgspfad.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define schildtxt10Width 18
#define schildtxt10Height 4
#define schildtxt10Bank 0

extern unsigned char schildtxt10[];

/* End of SCHILDTXT10.H */
