/*

 SCHILDTXT19.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __schildtxt19_h_INCLUDE
#define __schildtxt19_h_INCLUDE

#define schildtxt19Width 18
#define schildtxt19Height 4
#define schildtxt19Bank 0

extern const unsigned char schildtxt19[];

#endif

/* End of SCHILDTXT19.H */
