/*

 SCHILDTXT18.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : H:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\tempel-KG.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __schildtxt18_h_INCLUDE
#define __schildtxt18_h_INCLUDE

#define schildtxt18Width 18
#define schildtxt18Height 4
#define schildtxt18Bank 0

extern const unsigned char schildtxt18[];

#endif

/* End of SCHILDTXT18.H */
