/*

 SCHILDTXT16.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __schildtxt16_h_INCLUDE
#define __schildtxt16_h_INCLUDE

#define schildtxt16Width 18
#define schildtxt16Height 4
#define schildtxt16Bank 0

extern const unsigned char schildtxt16[];

#endif

/* End of SCHILDTXT16.H */
