/*

 SCHILDTXT1D.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define schildtxt1dWidth 18
#define schildtxt1dHeight 4
#define schildtxt1dBank 0

extern const unsigned char schildtxt1d[];

/* End of SCHILDTXT1D.H */
