/*

 SCHILDTXT15.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\verlies\gfx\entwuerfe\tilesets\mine-2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __schildtxt15_h_INCLUDE
#define __schildtxt15_h_INCLUDE

#define schildtxt15Width 18
#define schildtxt15Height 4
#define schildtxt15Bank 0

extern const unsigned char schildtxt15[];

#endif

/* End of SCHILDTXT15.H */
