/*

 SCHILDTXT7.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : c:\magister\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define schildtxt7Width 18
#define schildtxt7Height 4
#define schildtxt7Bank 0

extern const unsigned char schildtxt7[];

/* End of SCHILDTXT7.H */
