/*

 HUGOTXT1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hugotxt1Width 18
#define hugotxt1Height 4
#define hugotxt1Bank 0

extern unsigned char hugotxt1[];

/* End of HUGOTXT1.H */
