/*

 HUGOTXT4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : D:\owncloud\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_3.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define hugotxt4Width 18
#define hugotxt4Height 4
#define hugotxt4Bank 0

extern unsigned char hugotxt4[];

/* End of HUGOTXT4.H */
