/*

 XAVERTXT5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : O:\projekte\verlies-16x16\gfx\entwuerfe\tilesets\v_felsengrund_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define xavertxt5Width 18
#define xavertxt5Height 4
#define xavertxt5Bank 0

extern unsigned char xavertxt5[];

/* End of XAVERTXT5.H */
